### ISSUE TITLE
TODO　HTMLの修正

### ISSUE THREAD

**Issue by cyclengi** [cyclengi/corpingApp#4]
HTML改良の今後のTODOについて

- [x] header main footer を作成　分割する
- [x] header内容を作成　アプリ名とメニューを表示（ページによっては表示しない。ソース内のコメント参照）
- [x] footer内容作成　まずは簡単なコピーライト、アプリ名程度でよい
- [x] main内容作成　div class="haeder"とdiv class="inner"で分ける。

**Comment by cyclengi** [comment]
すべての作業を完了。issueを閉じる
